### ISSUE TITLE
Gulp concat seems to have issue with gulp sourcemaps

### ISSUE THREAD

**Issue by sachinsingh-nodejs** [contra/gulp-concat#135]
I get following error when I use gulp sourcemaps with concat

Error: Invalid mapping: {"generated":{"line":1,"column":9},"source":"bootstrap/mixins/_clearfix.scss","original":{"line":14,"column":-7},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (D:\POCs\RIC_Redesign\node_modules\source-map\lib\source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (D:\POCs\RIC_Redesign\node_modules\source-map\lib\source-map-generator.js:101:12)
    at D:\POCs\RIC_Redesign\node_modules\concat-with-sourcemaps\index.js:60:28
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (D:\POCs\RIC_Redesign\node_modules\source-map\lib\source-map-consumer.js:155:14)
    at Concat.add (D:\POCs\RIC_Redesign\node_modules\concat-with-sourcemaps\index.js:58:18)
    at DestroyableTransform.bufferContents [as _transform] (D:\POCs\RIC_Redesign\node_modules\gulp-concat\index.js:68:12)
    at DestroyableTransform.Transform._read (D:\POCs\RIC_Redesign\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (D:\POCs\RIC_Redesign\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (D:\POCs\RIC_Redesign\node_modules\readable-stream\lib\_stream_writable.js:347:64)
    at writeOrBuffer (D:\POCs\RIC_Redesign\node_modules\readable-stream\lib\_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (D:\POCs\RIC_Redesign\node_modules\readable-stream\lib\_stream_writable.js:274:11)
    at DestroyableTransform.ondata (D:\POCs\RIC_Redesign\node_modules\readable-stream\lib\_stream_readable.js:546:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at readableAddChunk (D:\POCs\RIC_Redesign\node_modules\readable-stream\lib\_stream_readable.js:217:18)

**Comment by contra** [comment]
Can you provide a full code sample?

**Comment by giosh94mhz** [comment]
Same issue for me, but it seems not related to `concat`.

The [bug is in libsass](https://github.com/sass/libsass/issues/2312) and [confirmed in gulp-sass](https://github.com/dlmanning/gulp-sass/issues/577), but not fixed yet.

As a workaround, downgrade `gulp-sass` to `^2.3.2`

**Comment by mahnunchik** [comment]
Any news?

**Comment by contra** [comment]
Bug is with another library (`libsass`) not gulp-concat so I'm going to close this. Needs to be fixed in libsass.
